#
# Copyright 2017-2018 The Jaeger Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: allrecipes-parser
    labels:
      app: eCookbook
      jaeger-infra: allrecipes-parser-deployment
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: jaeger
          jaeger-infra: allrecipes-parser-pod
      spec:
        containers:
        - image: mihad/allrecipes_parser
          name: allrecipes-parser
          resources: # (miha) added resources
            requests:
              memory: 10Mi 
              cpu: 100m
            limits:
              memory: 100Mi
              cpu: 0.5
          ports:
          - containerPort: 4007
            protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    name: allrecipes-parser
    labels:
      app: eCookbook
      jaeger-infra: allrecipes-parser-service
    annotations: #(miha) request for internal IP
    #cloud.google.com/load-balancer-type: "Internal"
  spec:
    ports:
    - name: allrecipes-parser
      port: 80
      protocol: TCP
      targetPort: 4007
    selector:
      jaeger-infra: allrecipes-parser-pod
    type: LoadBalancer
    #loadBalancerIP: 10.4.0.7 # (miha) resrved internal IP https://kubernetes.io/docs/concepts/services-networking/service/
