apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: allrecipes-parser
    labels:
      app: ecookbook
      cookbook-infra: allrecipes-parser-deployment
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ecookbok
          cookbook-infra: allrecipes-parser-pod
      spec:
        containers:
        - image: mihad/allrecipes_parser
          name: allrecipes-parser
          ports:
          - containerPort: 4007
            protocol: TCP
- apiVersion: extensions/v1beta1 ##############
  kind: Deployment
  metadata:
    name: ecookbook
    labels:
      app: ecookbook
      cookbook-infra: ecookbook-deployment
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ecookbook
          cookbook-infra: ecookbook-pod
      spec:
        containers:
        - image: mihad/ecookbook
          name: ecookbook
          env:
            - name: ALLRECIPES_MIDDLEWARE_HOST_PORT
              value: "allrecipes-parser:80"
            - name: CHEF_DB_HOST
              value: "ecookbook-vss-psql-postgresql"
          ports:
          - containerPort: 4006
            protocol: TCP #################################
- apiVersion: v1
  kind: Service
  metadata:
    name: allrecipes-parser
    labels:
      app: ecookbook
      cookbook-infra: allrecipes-parser-service
  spec:
    ports:
    - name: allrecipes-parser
      port: 80
      protocol: TCP
      targetPort: 4007
    selector:
      cookbook-infra: allrecipes-parser-pod
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    name: ecookbook
    labels:
      app: ecookbook
      cookbook-infra: ecookbook-service
  spec:
    ports:
    - name: ecookbook
      port: 80
      protocol: TCP
      targetPort: 4006
    selector:
      cookbook-infra: ecookbook-pod
    type: LoadBalancer
